[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.35"
no_match_coverage = "(test|script|interaction)"
evm_version = "prague"
fs_permissions = [
    { access = "read-write", path = "./logs" },
    { access = "read", path = "./broadcast" }
]
ignored_warnings_from = ["lib/forge-std/"]

[profile.release]
optimizer = true
#0-1000
optimizer_runs = 1000 #0
via_ir = true
gas_reports_ignore = ["StorageMigrator", "PureRouterAdapter", "AppendRouterAdapter"]
fuzz = { runs = 256 }

[lint]
exclude_lints = [
    "mixed-case-function", 
    "screaming-snake-case-const", 
    "screaming-snake-case-immutable",
    "unaliased-plain-import",
    # "unused-import",
    # "unwrapped-modifier-logic",
    "mixed-case-variable",
    "pascal-case-struct",
    "unsafe-cheatcode"
]

[fuzz]
runs = 16

[profile.ci.fuzz]
runs = 128

[profile.full.fuzz]
runs = 256

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
