[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.33"
no_match_coverage = "(test|script)"
evm_version = "prague"

[profile.release]
optimizer = true
#0-1000
optimizer_runs = 1000 #0
via_ir = true

[lint]
exclude_lints = [
    "mixed-case-function", 
    "screaming-snake-case-const", 
    "screaming-snake-case-immutable",
    "unaliased-plain-import",
    "unused-import",
    "unwrapped-modifier-logic",
    "mixed-case-variable",
    "pascal-case-struct"
]

[fuzz]
runs = 64

[profile.ci.fuzz]
runs = 128

[profile.full.fuzz]
runs = 256

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
